apiVersion: 1

datasources:
  - name: prometheus-metrics
    editable: true
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: sqlserver-metrics
    editable: true
    type: mssql
    access: proxy
    url: sqlserver:1433
    database: RegioesDb
    user: sa
    password: SenhaForte#369