apiVersion: v1
kind: Service
metadata:
  labels:
    app: regiao
  name: regiao-svc
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: regiao-api
  type: NodePort