name: API Contatos .NET Core

on:
  push:
    branches: [ "main", "features/anti-corruption-layer" ]
  pull_request:
    branches: [ "main", "features/anti-corruption-layer" ]

jobs:

  build:

    runs-on: ubuntu-latest                               

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build and execute tests
      run: |
        dotnet build --configuration Release
        dotnet test --configuration Release